import type { NextPage } from 'next'
import Head from 'next/head'
import {
  ContactSection,
  FAQSection,
  Footer,
  HeroSection,
  NavBar,
  ServicesSection,
  TeamSection,
  TestimonialsSection,
} from '../components'
import { ToolsetsSection } from '../components/ToolsetsSection'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <HeroSection />
      <ToolsetsSection />
      <ServicesSection />
      <TeamSection />
      <FAQSection />
      {/* <TestimonialsSection /> */}
      <ContactSection />
      <Footer />
    </div>
  )
}

export default Home
