import type { NextPage } from 'next'
import Head from 'next/head'
import {
  HeroSection,
  NavBar,
  ServicesSection,
} from '../components'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <HeroSection />
      <ServicesSection />
    </div>
  )
}

export default Home
